=begin
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
=end

class Problem12
  def triangle_with_divisors n
    triangle = 1
    step = 1
    until factors(triangle).size > n 
      step = step + 1
      triangle = triangle + step
    end
    
    triangle
  end
  
  def triangles n
    t = [0]
    (1..n).each { |i| 
      t.unshift (t.first + i)
    }
    
    t.reverse!
    t.delete_at(0)
    t
  end
  
  def factors n
    f = []
    (1..Math.sqrt(n).to_i).each { |i| 
      if (n % i == 0) then
        f.push(i)
        f.push(n / i)
      end 
    }
    # convenience
    f.sort!
    f
  end
  
end